routes/web.php
<?php

use App\Http\Controllers\CarouselController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PostCRUDController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\StudentController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/', [PagesController::class, 'index'])->name('index');
Route::get('/search', [PagesController::class, 'search'])->name('search');
Route::get('/genre-fantasy', [PagesController::class, 'genre_fantasy'])->name('genre-fantasy');
Route::get('/genre-romance', [PagesController::class, 'genre_romance'])->name('genre-romance');
Route::get('/genre-action', [PagesController::class, 'genre_action'])->name('genre-action');
Route::get('/anime-details/{id}', [PagesController::class, 'detail'])->name('anime-details');
Route::get('/home', [HomeController::class, 'index'])->name('home');
// Route::get('/login', [App\Http\Controllers\AuthenticationController::class, 'login'])->name('login');
// Route::post('/loginPost', [App\Http\Controllers\AuthenticationController::class, 'loginPost'])->name('loginPost');
Route::get('/contact', [PagesController::class, 'contact'])->name('contact');
Route::post('/contactPost', [PagesController::class, 'contactPost'])->name('contactPost');
// Route::get('/dashboard', [PagesController::class, 'dashboard'])->middleware('auth')->name('dashboard');

Route::post('/commentPost/', [PagesController::class, 'commentPost'])->name('commentPost');
// Route::get('/delete/{id}', [ContactController::class, 'delete'])->middleware('auth')->name('delete_contacts');
// Route::post('/delete/{id}', [ContactController::class, 'delete'])->middleware('auth')->name('delete_contacts');
Route::middleware(['auth'])->group(function () {
    Route::resource('dashboards', PostCRUDController::class);
    Route::resource('carousels', CarouselController::class);
    Route::get('/contacts', [ContactController::class, 'index'])->name('contacts');
});

app/Models/Carousel.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Carousel extends Model
{
    use HasFactory;

    protected $fillable = [
        'title', 'description', 'genre', 'link_download'
    ];
}

app/Http/Controllers/CarouselController.php
<?php

namespace App\Http\Controllers;

use App\Models\Carousel;
use Illuminate\Http\Request;

class CarouselController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $carousels['carousels'] = Carousel::orderBy('id','desc')->paginate(5);

        return view('carousels.index', $carousels);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('carousels.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required',
            'image' => 'required|image|mimes:jpg,png,jpeg,gif,svg|max:2048',
            'description' => 'required',
            'genre' => 'required',
            'link_download' => 'required',
        ]);
        $path = $request->file('image')->store('public/hero');
        $carousel = new Carousel;
        $carousel->title = $request->title;
        $carousel->description = $request->description;
        $carousel->genre = $request->genre;
        $carousel->link_download = $request->link_download;
        $carousel->image = $path;
        $carousel->save();

        return redirect()->route('carousels.index')
                        ->with('success','has been created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\carousel  $carousel
     * @return \Illuminate\Http\Response
     */
    public function show(Carousel $carousel)
    {
        return view('carousels.show',compact('carousel'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\carousel  $carousel
     * @return \Illuminate\Http\Response
     */
    public function edit(Carousel $carousel)
    {
        return view('carousels.edit',compact('carousel'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\carousel  $carousel
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'title' => 'required',
            'description' => 'required',
            'genre' => 'required',
            'link_download' => 'required',
        ]);

        $carousel = Carousel::find($id);
        if($request->hasFile('image')){
            $request->validate([
              'image' => 'required|image|mimes:jpg,png,jpeg,gif,svg|max:2048',
            ]);
            $path = $request->file('image')->store('public/hero');
            $carousel->image = $path;
        }
        $carousel->title = $request->title;
        $carousel->description = $request->description;
        $carousel->genre = $request->genre;
        $carousel->link_download = $request->link_download;
        $carousel->save();

        return redirect()->route('carousels.index')
                        ->with('success','updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Carousel  $carousel
     * @return \Illuminate\Http\Response
     */
    public function destroy(Carousel $carousel)
    {
        $carousel->delete();

        return redirect()->route('carousels.index')
                        ->with('success','has been deleted successfully');
    }
}

resources/views/carousels/create.blade.php
@extends('layouts.dashboard')
@section('content')
            <div class="breadcome-area">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="breadcome-list">
                                <div class="row">
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                        <div class="breadcomb-wp">
											<div class="breadcomb-icon">
												<i class="icon nalika-home"></i>
											</div>
											<div class="breadcomb-ctn">
												<h2>Add Carousel</h2>
												<p>Welcome to Animol <span class="bread-ntd"></span></p>
											</div>
										</div>
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                      <form action="{{ route('carousels.index') }}" method="GET">
                                        <div class="breadcomb-report custom-pro-edt-ds">
											<button type="submit" class="btn btn-ctl-bt waves-effect waves-light m-r-10">Back</button>
                                        </div>
                                      </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
            <!-- Single pro tab start-->
            <div class="single-product-tab-area mg-b-30">
                <!-- Single pro tab review Start-->
                <div class="single-pro-review-area">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <div class="review-tab-pro-inner">
                                    <ul id="myTab3" class="tab-review-design">
                                        <li class="active"><a href="#description"><i class="icon nalika-edit" aria-hidden="true"></i> Add Carousel</a></li>
                                    </ul>
                                    <div id="myTabContent" class="tab-content custom-product-edit">
                                        @if(session('status'))
                                            <div class="alert alert-success mb-1 mt-1">
                                                {{ session('status') }}
                                            </div>
                                        @endif
                                        <form action="{{ route('carousels.store') }}" method="POST" enctype="multipart/form-data">
                                            @csrf
                                            <div class="product-tab-list tab-pane fade active in" id="description">
                                                <div class="row">
                                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                        <div class="review-content-section">
                                                            <div class="input-group mg-b-pro-edt">
                                                                <span class="input-group-addon"><i class="icon nalika-user" aria-hidden="true"></i></span>
                                                                <input type="text" name="title" class="form-control" placeholder="Carousel Title">
                                                                @error('title')
                                                                <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                                                                @enderror
                                                            </div>
                                                            <div class="input-group mg-b-pro-edt">
                                                                <span class="input-group-addon"><i class="icon nalika-edit" aria-hidden="true"></i></span>
                                                                <input type="file" name="image" class="form-control" placeholder="Image">
                                                                @error('image')
                                                                <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                                                                @enderror
                                                            </div>

                                                        </div>
                                                    </div>
                                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                        <div class="review-content-section">
                                                            <div class="input-group mg-b-pro-edt">
                                                                <span class="input-group-addon"><i class="fa fa-usd" aria-hidden="true"></i></span>
                                                                <textarea type="text" name="description" class="form-control" style="height:150px" placeholder="Description"></textarea>
                                                                @error('description')
                                                                <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                                                                @enderror
                                                            </div>
                                                            <div class="input-group mg-b-pro-edt">
                                                                <span class="input-group-addon"><i class="fa fa-usd" aria-hidden="true"></i></span>
                                                                <input type="text" name="genre" class="form-control" placeholder="Genre">
                                                                @error('genre')
                                                                <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                                                                @enderror
                                                            </div>
                                                            <div class="input-group mg-b-pro-edt">
                                                                <span class="input-group-addon"><i class="fa fa-usd" aria-hidden="true"></i></span>
                                                                <input type="text" name="link_download" class="form-control" placeholder="Link Download">
                                                                @error('link_download')
                                                                <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                                                                @enderror
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                        <div class="text-center custom-pro-edt-ds">
                                                            <button type="submit" class="btn btn-ctl-bt waves-effect waves-light m-r-10">Save</button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
@endsection

resources/views/carousels/edit.blade.php
@extends('layouts.dashboard')
@section('content')
            <div class="breadcome-area">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="breadcome-list">
                                <div class="row">
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                        <div class="breadcomb-wp">
											<div class="breadcomb-icon">
												<i class="icon nalika-home"></i>
											</div>
											<div class="breadcomb-ctn">
												<h2>Edit Carousel</h2>
												<p>Welcome to Animol <span class="bread-ntd"></span></p>
											</div>
										</div>
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                      <form action="{{ route('carousels.index') }}" method="GET">
                                        <div class="breadcomb-report custom-pro-edt-ds">
											<button type="submit" class="btn btn-ctl-bt waves-effect waves-light m-r-10">Back</button>
                                        </div>
                                      </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
            <!-- Single pro tab start-->
            <div class="single-product-tab-area mg-b-30">
                <!-- Single pro tab review Start-->
                <div class="single-pro-review-area">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                <div class="review-tab-pro-inner">
                                    <ul id="myTab3" class="tab-review-design">
                                        <li class="active"><a href="#description"><i class="icon nalika-edit" aria-hidden="true"></i> Add Carousel</a></li>
                                    </ul>
                                    <div id="myTabContent" class="tab-content custom-product-edit">
                                        @if(session('status'))
                                            <div class="alert alert-success mb-1 mt-1">
                                                {{ session('status') }}
                                            </div>
                                        @endif
                                        <form action="{{ route('carousels.update',$carousel->id) }}" method="POST" enctype="multipart/form-data">
                                            @csrf
                                            @method('PUT')
                                            <div class="product-tab-list tab-pane fade active in" id="description">
                                                <div class="row">
                                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                        <div class="review-content-section">
                                                            <div class="input-group mg-b-pro-edt">
                                                                <span class="input-group-addon"><i class="icon nalika-user" aria-hidden="true"></i></span>
                                                                <input type="text" name="title" value="{{ $carousel->title }}" class="form-control" placeholder="Anime Title">
                                                                @error('title')
                                                                <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                                                                @enderror
                                                            </div>
                                                            <div class="input-group mg-b-pro-edt">
                                                                <span class="input-group-addon"><i class="icon nalika-edit" aria-hidden="true"></i></span>
                                                                <input type="file" name="image" class="form-control" placeholder="Image">
                                                                @error('image')
                                                                <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                                                                @enderror
                                                            </div>
                                                            <div class="input-group mg-b-pro-edt">
                                                                <img src="{{ Storage::url('app/'.$carousel->image) }}" height="200" width="200" alt="" />
                                                            </div>

                                                        </div>
                                                    </div>
                                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                        <div class="review-content-section">
                                                            <div class="input-group mg-b-pro-edt">
                                                                <span class="input-group-addon"><i class="fa fa-usd" aria-hidden="true"></i></span>
                                                                <textarea type="text" name="description" class="form-control" style="height:150px" placeholder="Description">{{ $carousel->description }}</textarea>
                                                                @error('description')
                                                                <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                                                                @enderror
                                                            </div>
                                                            <div class="input-group mg-b-pro-edt">
                                                                <span class="input-group-addon"><i class="fa fa-usd" aria-hidden="true"></i></span>
                                                                <input type="text" name="genre" value="{{ $carousel->genre }}" class="form-control" placeholder="Link Download">
                                                                @error('genre')
                                                                <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                                                                @enderror
                                                            </div>
                                                            <div class="input-group mg-b-pro-edt">
                                                                <span class="input-group-addon"><i class="fa fa-usd" aria-hidden="true"></i></span>
                                                                <input type="text" name="link_download" value="{{ $carousel->link_download }}" class="form-control" placeholder="Link Download">
                                                                @error('link_download')
                                                                <div class="alert alert-danger mt-1 mb-1">{{ $message }}</div>
                                                                @enderror
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                        <div class="text-center custom-pro-edt-ds">
                                                            <button type="submit" class="btn btn-ctl-bt waves-effect waves-light m-r-10">Save</button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
@endsection

resources/views/carousels/index.blade.php
@extends('layouts.dashboard')
@section('content')
            <div class="breadcome-area">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="breadcome-list">
                                <div class="row">
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                        <div class="breadcomb-wp">
											<div class="breadcomb-icon">
												<i class="icon nalika-home"></i>
											</div>
											<div class="breadcomb-ctn">
												<h2>Carousel List</h2>
												<p>Welcome to Animol <span class="bread-ntd">Admin</span></p>
											</div>
										</div>
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="product-status mg-b-30">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="product-status-wrap">
                            <h4>Anime List</h4>
                            <div class="add-product">
                                <a href="{{ route('carousels.create') }}">Add Carousel</a>
                            </div>
                            <table>
                                <tr>
                                    <th>No.</th>
                                    <th>Image</th>
                                    <th>Carousel Title</th>
                                    <th>Description</th>
                                    <th>Genre</th>
                                    <th>Link</th>
                                    <th>Setting</th>
                                </tr>
                                @foreach ($carousels as $carousel)
                                <tr>
                                    <td>{{ $carousel->id }}</td>
                                    <td><img src="{{ Storage::url($carousel->image) }}" alt="" /></td>
                                    <td>{{ $carousel->title }}</td>
                                    <td>{{ $carousel->description }}</td>
                                    <td>{{ $carousel->genre }}</td>
                                    <td>{{ $carousel->link_download }}</td>
                                    <td>
                                        <form action="{{ route('carousels.destroy',$carousel->id) }}" method="POST">

                                            <a class="btn btn-primary" href="{{ route('carousels.edit',$carousel->id) }}">Edit</a>
                                            <a class="btn btn-info" href="{{ route('index') }}">Show</a>
                                            @csrf
                                            @method('DELETE')

                                            <button type="submit" class="btn btn-danger">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            </table>
                            <div class="custom-pagination">
								<ul class="pagination">
									{!! $carousels->links() !!}
								</ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
@endsection