routes/web.php
<?php

use App\Http\Controllers\CarouselController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PagesController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PostCRUDController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\StudentController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/', [PagesController::class, 'index'])->name('index');
Route::get('/search', [PagesController::class, 'search'])->name('search');
Route::get('/genre-fantasy', [PagesController::class, 'genre_fantasy'])->name('genre-fantasy');
Route::get('/genre-romance', [PagesController::class, 'genre_romance'])->name('genre-romance');
Route::get('/genre-action', [PagesController::class, 'genre_action'])->name('genre-action');
Route::get('/anime-details/{id}', [PagesController::class, 'detail'])->name('anime-details');
Route::get('/home', [HomeController::class, 'index'])->name('home');
// Route::get('/login', [App\Http\Controllers\AuthenticationController::class, 'login'])->name('login');
// Route::post('/loginPost', [App\Http\Controllers\AuthenticationController::class, 'loginPost'])->name('loginPost');
Route::get('/contact', [PagesController::class, 'contact'])->name('contact');
Route::post('/contactPost', [PagesController::class, 'contactPost'])->name('contactPost');
// Route::get('/dashboard', [PagesController::class, 'dashboard'])->middleware('auth')->name('dashboard');

Route::post('/commentPost/', [PagesController::class, 'commentPost'])->name('commentPost');
// Route::get('/delete/{id}', [ContactController::class, 'delete'])->middleware('auth')->name('delete_contacts');
// Route::post('/delete/{id}', [ContactController::class, 'delete'])->middleware('auth')->name('delete_contacts');
Route::middleware(['auth'])->group(function () {
    Route::resource('dashboards', PostCRUDController::class);
    Route::resource('carousels', CarouselController::class);
    Route::get('/contacts', [ContactController::class, 'index'])->name('contacts');
});

app/Models/Dashboard.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Dashboard extends Model
{
    use HasFactory;

    protected $fillable = [
        'title', 'description', 'type', 'episode', 'genre', 'duration', 'link_480p_uptobox', 'link_480p_acefile', 'link_480p_googledrive', 'link_720p_uptobox', 'link_720p_acefile', 'link_720p_googledrive', 'link_1080p_uptobox', 'link_1080p_acefile', 'link_1080p_googledrive'
    ];
}

resources/views/dashboards/index.blade.php
@extends('layouts.dashboard')
@section('content')
            <div class="breadcome-area">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<div class="breadcome-list">
                                <div class="row">
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                        <div class="breadcomb-wp">
											<div class="breadcomb-icon">
												<i class="icon nalika-home"></i>
											</div>
											<div class="breadcomb-ctn">
												<h2>Anime List</h2>
												<p>Welcome to Nalika <span class="bread-ntd">Admin</span></p>
											</div>
										</div>
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="product-status mg-b-30">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                        <div class="product-status-wrap">
                            <h4>Anime List</h4>
                            <div class="add-product">

                            </div>
                            <table>
                                <tr>
                                    <th>No.</th>
                                    <th>Image</th>
                                    <th>Anime Title</th>
                                    <th>Description</th>
                                    <th>Type</th>
                                    <th>Genre</th>
                                    <th>Episode</th>
                                    <th>Duration</th>
                                    {{-- <th>Link 480p Uptobox</th>
                                    <th>Link 480p Acefile</th>
                                    <th>Link 480p Googledrive</th>
                                    <th>Link 720p Uptobox</th>
                                    <th>Link 720p Acefile</th>
                                    <th>Link 720p Googledrive</th>
                                    <th>Link 1080p Uptobox</th>
                                    <th>Link 1080p Acefile</th>
                                    <th>Link 1080p Googledrive</th> --}}
                                    <th>Setting</th>
                                </tr>
                                @foreach ($dashboards as $dashboard)
                                <tr>
                                    <td>{{ ++$i }}</td>
                                    <td><img src="{{ Storage::url($dashboard->image) }}" alt="" /></td>
                                    <td>{{ $dashboard->title }}</td>
                                    <td>{{ $dashboard->description }}</td>
                                    <td>{{ $dashboard->type }}</td>
                                    <td>{{ $dashboard->genre }}</td>
                                    <td>{{ $dashboard->episode }}</td>
                                    <td>{{ $dashboard->duration }}</td>
                                    {{-- <td>{{ $dashboard->link_480p_uptobox }}</td>
                                    <td>{{ $dashboard->link_480p_acefile }}</td>
                                    <td>{{ $dashboard->link_480p_googledrive }}</td>
                                    <td>{{ $dashboard->link_720p_uptobox }}</td>
                                    <td>{{ $dashboard->link_720p_acefile }}</td>
                                    <td>{{ $dashboard->link_720p_googledrive }}</td>
                                    <td>{{ $dashboard->link_1080p_uptobox }}</td>
                                    <td>{{ $dashboard->link_1080p_acefile }}</td>
                                    <td>{{ $dashboard->link_1080p_googledrive }}</td> --}}
                                    <td>
                                        <form action="{{ route('dashboards.destroy',$dashboard->id) }}" method="POST">

                                            <a class="btn btn-primary" href="{{ route('dashboards.edit',$dashboard->id) }}">Edit</a>

                                            <a class="btn btn-info" href="{{ route('anime-details',$dashboard->id) }}">Show</a>

                                            @csrf
                                            @method('DELETE')

                                            <button type="submit" class="btn btn-danger">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            </table>
                            <div class="custom-pagination">
                                <ul class="pagination">
                                    {!! $dashboards->links() !!}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
@endsection